title: Sun Ryung Park
description: Political Scientist
I am a political scientist specializing in green industrial policy, energy transition politics, and the comparative political economy of East Asia. My research focuses in particular on Korea, Japan, and Taiwan.
theme: minima

header_pages:
  - about.md
  - publications.md
  - policy-work.md
  - teaching.md
  - cv.md
  - contact.md
