title: Sun Ryung Park
description: Political Scientist
theme: minima

header_pages:
  - about.md
  - publications.md
  - policy-work.md
  - teaching.md
  - cv.md
  - contact.md

permalink: /:title/

copyright: "© 2026 Sun Ryung Park"

